/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Variant({
  'twelveWheel' : IDL.Null,
  'tractor' : IDL.Null,
});
export const DeliveryType = IDL.Variant({
  'local' : IDL.Null,
  'outside' : IDL.Null,
});
export const BrickSelection = IDL.Record({
  'quantity' : IDL.Nat,
  'brickType' : IDL.Text,
});
export const CompleteDelivery = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'vehicleType' : VehicleType,
  'date' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'calculatedAmount' : IDL.Float64,
  'unloadingLabor' : IDL.Vec(IDL.Text),
  'brickSelections' : IDL.Vec(BrickSelection),
  'loadingLabor' : IDL.Vec(IDL.Text),
  'deliveryType' : DeliveryType,
  'distance' : IDL.Float64,
  'batsNotes' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'dueAmount' : IDL.Float64,
});
export const PendingDelivery = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'brickSelections' : IDL.Vec(BrickSelection),
  'deliveryType' : DeliveryType,
  'distance' : IDL.Float64,
  'batsNotes' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'dueAmount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addVehicle' : IDL.Func([VehicleType, IDL.Text], [], []),
  'createPendingDelivery' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        DeliveryType,
        IDL.Vec(BrickSelection),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deletePendingDelivery' : IDL.Func([IDL.Nat], [], []),
  'getAllCompleteDeliveries' : IDL.Func(
      [],
      [IDL.Vec(CompleteDelivery)],
      ['query'],
    ),
  'getAllPendingDeliveries' : IDL.Func(
      [],
      [IDL.Vec(PendingDelivery)],
      ['query'],
    ),
  'removeVehicle' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Variant({
    'twelveWheel' : IDL.Null,
    'tractor' : IDL.Null,
  });
  const DeliveryType = IDL.Variant({
    'local' : IDL.Null,
    'outside' : IDL.Null,
  });
  const BrickSelection = IDL.Record({
    'quantity' : IDL.Nat,
    'brickType' : IDL.Text,
  });
  const CompleteDelivery = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'vehicleType' : VehicleType,
    'date' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'calculatedAmount' : IDL.Float64,
    'unloadingLabor' : IDL.Vec(IDL.Text),
    'brickSelections' : IDL.Vec(BrickSelection),
    'loadingLabor' : IDL.Vec(IDL.Text),
    'deliveryType' : DeliveryType,
    'distance' : IDL.Float64,
    'batsNotes' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'dueAmount' : IDL.Float64,
  });
  const PendingDelivery = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'brickSelections' : IDL.Vec(BrickSelection),
    'deliveryType' : DeliveryType,
    'distance' : IDL.Float64,
    'batsNotes' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'dueAmount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addVehicle' : IDL.Func([VehicleType, IDL.Text], [], []),
    'createPendingDelivery' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          DeliveryType,
          IDL.Vec(BrickSelection),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deletePendingDelivery' : IDL.Func([IDL.Nat], [], []),
    'getAllCompleteDeliveries' : IDL.Func(
        [],
        [IDL.Vec(CompleteDelivery)],
        ['query'],
      ),
    'getAllPendingDeliveries' : IDL.Func(
        [],
        [IDL.Vec(PendingDelivery)],
        ['query'],
      ),
    'removeVehicle' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };