/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrickSelection { 'quantity' : bigint, 'brickType' : string }
export interface CompleteDelivery {
  'id' : bigint,
  'customerName' : string,
  'vehicleType' : VehicleType,
  'date' : string,
  'vehicleNumber' : string,
  'calculatedAmount' : number,
  'unloadingLabor' : Array<string>,
  'brickSelections' : Array<BrickSelection>,
  'loadingLabor' : Array<string>,
  'deliveryType' : DeliveryType,
  'distance' : number,
  'batsNotes' : [] | [string],
  'address' : string,
  'dueAmount' : number,
}
export type DeliveryType = { 'local' : null } |
  { 'outside' : null };
export interface PendingDelivery {
  'id' : bigint,
  'customerName' : string,
  'date' : string,
  'brickSelections' : Array<BrickSelection>,
  'deliveryType' : DeliveryType,
  'distance' : number,
  'batsNotes' : [] | [string],
  'address' : string,
  'dueAmount' : number,
}
export type VehicleType = { 'twelveWheel' : null } |
  { 'tractor' : null };
export interface _SERVICE {
  'addVehicle' : ActorMethod<[VehicleType, string], undefined>,
  'createPendingDelivery' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      DeliveryType,
      Array<BrickSelection>,
      [] | [string],
    ],
    undefined
  >,
  'deletePendingDelivery' : ActorMethod<[bigint], undefined>,
  'getAllCompleteDeliveries' : ActorMethod<[], Array<CompleteDelivery>>,
  'getAllPendingDeliveries' : ActorMethod<[], Array<PendingDelivery>>,
  'removeVehicle' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];