/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PendingDelivery {
    id: bigint;
    customerName: string;
    date: string;
    brickSelections: Array<BrickSelection>;
    deliveryType: DeliveryType;
    distance: number;
    batsNotes?: string;
    address: string;
    dueAmount: number;
}
export interface CompleteDelivery {
    id: bigint;
    customerName: string;
    vehicleType: VehicleType;
    date: string;
    vehicleNumber: string;
    calculatedAmount: number;
    unloadingLabor: Array<string>;
    brickSelections: Array<BrickSelection>;
    loadingLabor: Array<string>;
    deliveryType: DeliveryType;
    distance: number;
    batsNotes?: string;
    address: string;
    dueAmount: number;
}
export interface BrickSelection {
    quantity: bigint;
    brickType: string;
}
export enum DeliveryType {
    local = "local",
    outside = "outside"
}
export enum VehicleType {
    twelveWheel = "twelveWheel",
    tractor = "tractor"
}
export interface backendInterface {
    addVehicle(vehicleType: VehicleType, vehicleNumber: string): Promise<void>;
    createPendingDelivery(date: string, customerName: string, address: string, dueAmount: number, distance: number, deliveryType: DeliveryType, brickSelections: Array<BrickSelection>, batsNotes: string | null): Promise<void>;
    deletePendingDelivery(id: bigint): Promise<void>;
    getAllCompleteDeliveries(): Promise<Array<CompleteDelivery>>;
    getAllPendingDeliveries(): Promise<Array<PendingDelivery>>;
    removeVehicle(vehicleNumber: string): Promise<void>;
}
import type { BrickSelection as _BrickSelection, CompleteDelivery as _CompleteDelivery, DeliveryType as _DeliveryType, PendingDelivery as _PendingDelivery, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addVehicle(arg0: VehicleType, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(to_candid_VehicleType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(to_candid_VehicleType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createPendingDelivery(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: DeliveryType, arg6: Array<BrickSelection>, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPendingDelivery(arg0, arg1, arg2, arg3, arg4, to_candid_DeliveryType_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPendingDelivery(arg0, arg1, arg2, arg3, arg4, to_candid_DeliveryType_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async deletePendingDelivery(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePendingDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePendingDelivery(arg0);
            return result;
        }
    }
    async getAllCompleteDeliveries(): Promise<Array<CompleteDelivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompleteDeliveries();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompleteDeliveries();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingDeliveries(): Promise<Array<PendingDelivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingDeliveries();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingDeliveries();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeVehicle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVehicle(arg0);
            return result;
        }
    }
}
function from_candid_CompleteDelivery_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompleteDelivery): CompleteDelivery {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryType): DeliveryType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PendingDelivery_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingDelivery): PendingDelivery {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    date: string;
    brickSelections: Array<_BrickSelection>;
    deliveryType: _DeliveryType;
    distance: number;
    batsNotes: [] | [string];
    address: string;
    dueAmount: number;
}): {
    id: bigint;
    customerName: string;
    date: string;
    brickSelections: Array<BrickSelection>;
    deliveryType: DeliveryType;
    distance: number;
    batsNotes?: string;
    address: string;
    dueAmount: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        date: value.date,
        brickSelections: value.brickSelections,
        deliveryType: from_candid_DeliveryType_n11(_uploadFile, _downloadFile, value.deliveryType),
        distance: value.distance,
        batsNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.batsNotes)),
        address: value.address,
        dueAmount: value.dueAmount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    vehicleType: _VehicleType;
    date: string;
    vehicleNumber: string;
    calculatedAmount: number;
    unloadingLabor: Array<string>;
    brickSelections: Array<_BrickSelection>;
    loadingLabor: Array<string>;
    deliveryType: _DeliveryType;
    distance: number;
    batsNotes: [] | [string];
    address: string;
    dueAmount: number;
}): {
    id: bigint;
    customerName: string;
    vehicleType: VehicleType;
    date: string;
    vehicleNumber: string;
    calculatedAmount: number;
    unloadingLabor: Array<string>;
    brickSelections: Array<BrickSelection>;
    loadingLabor: Array<string>;
    deliveryType: DeliveryType;
    distance: number;
    batsNotes?: string;
    address: string;
    dueAmount: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        vehicleType: from_candid_VehicleType_n9(_uploadFile, _downloadFile, value.vehicleType),
        date: value.date,
        vehicleNumber: value.vehicleNumber,
        calculatedAmount: value.calculatedAmount,
        unloadingLabor: value.unloadingLabor,
        brickSelections: value.brickSelections,
        loadingLabor: value.loadingLabor,
        deliveryType: from_candid_DeliveryType_n11(_uploadFile, _downloadFile, value.deliveryType),
        distance: value.distance,
        batsNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.batsNotes)),
        address: value.address,
        dueAmount: value.dueAmount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twelveWheel: null;
} | {
    tractor: null;
}): VehicleType {
    return "twelveWheel" in value ? VehicleType.twelveWheel : "tractor" in value ? VehicleType.tractor : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    local: null;
} | {
    outside: null;
}): DeliveryType {
    return "local" in value ? DeliveryType.local : "outside" in value ? DeliveryType.outside : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PendingDelivery>): Array<PendingDelivery> {
    return value.map((x)=>from_candid_PendingDelivery_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompleteDelivery>): Array<CompleteDelivery> {
    return value.map((x)=>from_candid_CompleteDelivery_n7(_uploadFile, _downloadFile, x));
}
function to_candid_DeliveryType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): _DeliveryType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    twelveWheel: null;
} | {
    tractor: null;
} {
    return value == VehicleType.twelveWheel ? {
        twelveWheel: null
    } : value == VehicleType.tractor ? {
        tractor: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): {
    local: null;
} | {
    outside: null;
} {
    return value == DeliveryType.local ? {
        local: null
    } : value == DeliveryType.outside ? {
        outside: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
